[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.61.1",
    "pyautogui>=0.9.54",
    "pygame>=2.6.1",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
